// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfbgF5sW0PEDZmgRkrQ5lxX2ZUehXZ5J4',
    appId: '1:940825212752:web:aef0de904e18883ea41e55',
    messagingSenderId: '940825212752',
    projectId: 'roadless-project-145d9',
    authDomain: 'roadless-project-145d9.firebaseapp.com',
    storageBucket: 'roadless-project-145d9.appspot.com',
    databaseURL: 'https://roadless-project-145d9-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFbCMV-ixwLRUkvfaZ-Kar-NGAHp2rRsE',
    appId: '1:940825212752:android:4a021a7610d9f850a41e55',
    messagingSenderId: '940825212752',
    projectId: 'roadless-project-145d9',
    storageBucket: 'roadless-project-145d9.appspot.com',
    databaseURL: 'https://roadless-project-145d9-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMwzB0GsNaWb8dUny18lWXMwxb_HEZDp8',
    appId: '1:940825212752:ios:17080f01222bc95aa41e55',
    messagingSenderId: '940825212752',
    projectId: 'roadless-project-145d9',
    storageBucket: 'roadless-project-145d9.appspot.com',
    iosBundleId: 'com.example.roadless',
    databaseURL: 'https://roadless-project-145d9-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMwzB0GsNaWb8dUny18lWXMwxb_HEZDp8',
    appId: '1:940825212752:ios:17080f01222bc95aa41e55',
    messagingSenderId: '940825212752',
    projectId: 'roadless-project-145d9',
    storageBucket: 'roadless-project-145d9.appspot.com',
    iosBundleId: 'com.example.roadless',
    databaseURL: 'https://roadless-project-145d9-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfbgF5sW0PEDZmgRkrQ5lxX2ZUehXZ5J4',
    appId: '1:940825212752:web:e5abf357f8bd3816a41e55',
    messagingSenderId: '940825212752',
    projectId: 'roadless-project-145d9',
    authDomain: 'roadless-project-145d9.firebaseapp.com',
    storageBucket: 'roadless-project-145d9.appspot.com',
    databaseURL: 'https://roadless-project-145d9-default-rtdb.europe-west1.firebasedatabase.app',
  );
}
